title: "Miette's blog"
subtitle: "One thought per sometimes"
description: "Rendering Engineer trying to reduce the bloat in fast and pretty pixels"
name: "Tristan Delort"
url: "https://tdelort.github.io/"
repository: "tdelort/tdelort.github.io"

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      author_profile: true
      comments: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default
      author_profile: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: default
      author_profile: true
      comments: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
    label: "comment"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

author:
  name     : "Tristan Delort"
  avatar   : "/assets/images/profile_placeholder_0.jpg"
  bio      : "Rendering Engineer. Worked at Spiders on GreedFall : The Dying World"
  location : "IDF, France"
  links:
    - label: "GitHub"
      icon: "/assets/images/github_icon.svg"
      url: "https://github.com/tdelort"
    - label: "LinkedIn"
      icon: "/assets/images/linkedin_icon.png"
      url: "https://www.linkedin.com/in/tristan-delort/"
    - label: "Email"
      icon: "/assets/images/mail_icon.svg"
      url: "mailto:tristan.delort@gmail.com"
    - label: "RSS"
      icon: "/assets/images/rss_icon.svg"
      url: "/feed.xml"

include:
  - _pages
exclude:
  - CHANGELOG
  - Gemfile
  - LICENSE
  - README